services:
  backend:
    image: moviemate-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SERVER_PORT: 5001
      SERVER_HOST: 0.0.0.0
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: pass123
      DB_DBNAME: database
      DB_TIMEZONE: America/New_York
      DB_SSL: disable


  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d database"]
      interval: 5s
      timeout: 5s
      retries: 5

    